#!/usr/bin/env bash
#Install nginx
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -ie "s/^server {$/server {\n\trewrite ^\/redirect_me https:\/\/www.google.com\/ permanent;/g" /etc/nginx/sites-available/default
service nginx restart
